# Generated by Django 6.0.3 on 2026-03-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('IT', 'IT'), ('OMA', 'OMA'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=20),
        ),
    ]
