# Generated by Django 6.0.3 on 2026-05-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='responded',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
