# Generated by Django 6.0.3 on 2026-05-16 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_add_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=10, unique=True)),
                ('resolution_hours', models.PositiveIntegerField(help_text='Horas máximas para resolver el ticket desde su creación')),
            ],
            options={
                'verbose_name': 'Política SLA',
                'verbose_name_plural': 'Políticas SLA',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('M365', 'Microsoft 365'), ('OUTLOOK', 'Outlook / Correo'), ('REDES', 'Redes'), ('EQUIPOS', 'Equipos / Hardware'), ('SEGURIDAD', 'Seguridad'), ('VPN', 'VPN / Acceso Remoto'), ('SHAREPOINT', 'SharePoint'), ('AZURE', 'Azure'), ('APPS', 'Aplicaciones Corporativas'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_met',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TicketWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Sesión de trabajo',
                'verbose_name_plural': 'Sesiones de trabajo',
                'ordering': ['-started_at'],
            },
        ),
    ]
