# Generated by Django 6.0.3 on 2026-05-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_sla_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
