# Generated by Django 6.0.3 on 2026-05-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_sla_warning_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('STATUS_CHANGE', 'Cambio de estado'), ('RESPONDED', 'Respuesta registrada'), ('FIELD_CHANGE', 'Campo modificado'), ('ESCALATED', 'Escalado automáticamente')], max_length=30),
        ),
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_notes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Nota interna',
                'verbose_name_plural': 'Notas internas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('M365', 'Microsoft 365'), ('OUTLOOK', 'Outlook / Correo'), ('REDES', 'Redes'), ('EQUIPOS', 'Equipos / Hardware'), ('SEGURIDAD', 'Seguridad'), ('VPN', 'VPN / Acceso Remoto'), ('SHAREPOINT', 'SharePoint'), ('AZURE', 'Azure'), ('APPS', 'Aplicaciones Corporativas'), ('OTRO', 'Otro')], max_length=20)),
                ('area', models.CharField(blank=True, choices=[('OMA', 'OMA'), ('OPERADOR', 'Operador')], default='', help_text='Dejar vacío para que aplique a todas las áreas.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'profile__role': 'IT'}, on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regla de enrutamiento',
                'verbose_name_plural': 'Reglas de enrutamiento',
                'ordering': ['category', 'area'],
                'unique_together': {('category', 'area')},
            },
        ),
    ]
