# Generated by Django 6.0.5 on 2026-06-02 18:21

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticketattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketnote',
            options={'ordering': ['created_at'], 'verbose_name': 'Nota / Comentario', 'verbose_name_plural': 'Notas / Comentarios'},
        ),
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('STATUS_CHANGE', 'Cambio de estado'), ('RESPONDED', 'Respuesta registrada'), ('FIELD_CHANGE', 'Campo modificado'), ('ESCALATED', 'Escalado automáticamente'), ('REOPENED', 'Reabierto por usuario'), ('ASSIGNED', 'Técnico asignado'), ('REASSIGNED', 'Técnico reasignado'), ('COMMENT_ADDED', 'Comentario agregado'), ('ATTACHMENT_ADDED', 'Adjunto agregado'), ('ATTACHMENT_DELETED', 'Adjunto eliminado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticketcounter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketroutingrule',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'profile__role__is_it_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
